### ISSUE TITLE
Not acknowledging "Run as Administrator" 

### ISSUE THREAD

**Issue by mikesimone** [CiscoSecurity/amp-05-health-checker-windows#10]
When I run as admin, it doesn't believe. 

![image](https://user-images.githubusercontent.com/35898917/128610563-2311c43c-d66b-47b7-a782-6b0afbaf78c6.png)

And I say yes...

![image](https://user-images.githubusercontent.com/35898917/128610598-abba6157-b7cf-417d-87b8-3320a21c5962.png)

And it informs me that I'm not, in fact, running as admin. 

![image](https://user-images.githubusercontent.com/35898917/128610610-44cd207f-6b83-4a0a-ac45-82ea64ec79cb.png)

- Version: Health_Checker_03_Aug_2021
- Secure Endpoint version: 7.4.1.20439
- Windows version: Windows 10 21H1 19043.1151

**Comment by mafranks** [comment]
@mikesimone can you provide associated logs for this?  I wasn't able to duplicate the issue.

**Comment by mafranks** [comment]
Was able to reproduce on a WebEx with @mikesimone and repro the issue.  It occurs when there is more than one directory with a build number such as x.x.x.xxxxx.  The program is pulling the 2nd to last directory instead of the last one and then attempts to launch sfc.exe from that directory which does not exist so the exception is hit and the program exits.  Should be a relatively easy fix.

**Comment by mafranks** [comment]
Fixed in latest commit.  Marking as resolved.
