### ISSUE TITLE
Cannot run, failed to load main_page.py

### ISSUE THREAD

**Issue by smalluk** [CiscoSecurity/amp-05-health-checker-windows#11]
Cannot run, "failed to execute script main_page" when loading using AMP_Health_Checker_03Aug2021.exe
![image](https://user-images.githubusercontent.com/35768515/132313688-17d9e8c0-9ce2-4655-b22f-f407af9de828.png)

**Comment by mafranks** [comment]
@smalluk can you provide some additional information as to how you're executing the program?  Are you double clicking the exe?  Are you executing the script manually from the CLI?  This issue is typically seen when a required file is missing.  The exe shouldn't have that problem but if you're using pyinstaller yourself and something is missing, it is possible to hit this error.

**Comment by mafranks** [comment]
Closing due to lack of additional data provided.  Will revisit this if someone else brings it up in the future and provided information.
