### ISSUE TITLE
Fatal error when run on a machine with Windows connector v7.5.7.21234

### ISSUE THREAD

**Issue by tpelayocc** [CiscoSecurity/amp-05-health-checker-windows#14]
When running AMP Health Checker on a computer with Windows connector v7.5.7.21234, a "Fatal error detected" dialog box pops up that says, "Failed to execute script main_page".

![image](https://user-images.githubusercontent.com/39174859/197015831-37e90bda-2236-4458-b70e-cf568d9e0362.png)

Log file:
[amp_health_checker_log.log](https://github.com/CiscoSecurity/amp-05-health-checker-windows/files/9832634/amp_health_checker_log.log)

**Comment by tpelayocc** [comment]
I believe the error is caused by this change with Windows Connector v7.5.7:
Beginning in Windows Connector 7.5.7, end users will no longer be able to read
the contents of the policy.xml file. Policy information can only be accessed by
users with privileges to view and edit the policy in the Secure Endpoint Console.
Exclusions will still be visible in the connector IP Tray user interface unless this
setting is disabled in the policy settings (“Hide exclusions” can be found under
“Client User Interface”). (CSCwc05323)

**Comment by mafranks** [comment]
You are correct on isolating the issue to the inability to read the policy.xml file.  The only way I can see to work around this is to require SecureX credentials and use the new v3 API call for Secure Endpoints to pull the policy information.
https://developer.cisco.com/docs/secure-endpoint/#!policies
If the SecureX credentials are available, you can make an edit starting on line 546 so instead of "root = self.get_root(path)" you would need to do something like "if os.path.exists(path):" then do everything on lines 548-558 as normal.  Else, implement the new v3 API call to pull the policy.xml and parse it instead.

**Comment by mafranks** [comment]
Fixed in the latest release.
