### ISSUE TITLE
Cannot run Health Checker Application

### ISSUE THREAD

**Issue by smalluk** [CiscoSecurity/amp-05-health-checker-windows#2]
Running version 7.4.1 and error as seen in screenshot - appears to be stuck on finding the version number.

Worked previously on 7.3.x

![image](https://user-images.githubusercontent.com/35768515/120662470-152c9280-c481-11eb-8d44-cd05a4e3ab98.png)

**Comment by bmacer** [comment]
fixed with https://github.com/CiscoSecurity/amp-05-health-checker-windows/commit/ddb4dfd6c478b2a55253d85b0a1aa6851047be95
please use AMP_Health_Checker_14July2021.exe, should not encounter this issue.
for what it's worth, the cause was that Secure Endpoint (formerly AMP) since 7.4.1 started using the build number in the folder path, which killed the logic.
